name: waterdemand
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - geopandas
  - cartopy>=0.21
  - notebook
  - rasterio
  - matplotlib
  - Ipython
  - folium
  - sentinelsat
  - numpy
  - skikit-learn
  - opencv
